PROJECT_STATUS_NOT_STARTED = 0
PROJECT_STATUS_ONGOING = 1
PROJECT_STATUS_COMPLETED = 2
PROJECT_STATUS_ON_HOLD = 3
PROJECT_STATUS_DELETED = 4

TASK_STATUS_FREE = 0
TASK_STATUS_ASSIGNED = 1
TASK_STATUS_IN_PROGRESS = 2
TASK_STATUS_DONE = 3
TASK_STATUS_DELETED = 4